quotes = [
  ["Science doesn't purvey absolute truth. Science is a mechanism. It's a way of trying to improve your knowledge of nature. It's a system for testing your thoughts against the universe and seeing whether they match. And this works, not just for the ordinary aspects of science, but for all of life. I should think people would want to know that what they know is truly what the universe is like, or at least as close as they can get to it.", "Isaac Asimov"],
  ["We often frame our understanding of what the space telescope will do in terms of what we expect to find, and actually it would be terribly anticlimactic if in fact we find what we expect to find. … The most important discoveries will provide answers to questions that we do not yet know how to ask and will concern objects we have not yet imagined.", "John N. Bahcall"],
  ["People keep saying \"science doesn't know everything!\" Well, science \"knows\" it doesn't know everything; otherwise it would stop.", "Dara Ó Briain"],
  ["To spread healthy ideas among even the lowest classes of people, to remove men from the influence of prejudice and passion, to make reason the arbiter and supreme guide of public opinion; that is the essential goal of the sciences; that is how science will contribute to the advancement of civilization, and that is what deserves protection of governments who want to insure the stability of their power.", "Georges Cuvier"],
  ["It is those who know little, and not those who know much, who so positively assert that this or that problem will never be solved by science.", "Charles Darwin"],
  ["Finding hidden links between seemingly disparate phenomena is what makes the scientific method so powerful and compelling. The distinctive feature of science is that it is both broad and deep: broad in the way it tackles all physical phenomena and deep in the way it weaves them, economically, into a common explanatory scheme requiring fewer and fewer assumptions. No other system of thought can match its breadth and depth.", "Paul Davies"],
  ["Fortunately science, like that nature to which it belongs, is neither limited by time nor by space. It belongs to the world, and is of no country and of no age. The more we know, the more we feel our ignorance; the more we feel how much remains unknown; and in philosophy, the sentiment of the Macedonian hero can never apply, — there are always new worlds to conquer.", "Sir Humphry Davy"],
  ["Our freedom to doubt was born out of a struggle against authority in the early days of science. It was a very deep and strong struggle: permit us to question — to doubt — to not be sure. I think that it is important that we do not forget this struggle and thus perhaps lose what we have gained.", "Richard Feynman"],
  ["Science is a way of trying not to fool yourself. The first principle is that you must not fool yourself, and you are the easiest person to fool.", "Richard Feynman"],
  ["And most people say of astrology, \"Oh, it's harmless fun, isn't it?\" And I should say probably for about 80% of the cases it probably is harmless fun, but there's a strong way in which it isn't harmless: one, because it's so anti-science; you know, you'll hear things like \"Science doesn't know everything.\" Well, of course science doesn't know everything. But because science doesn't know everything that doesn't mean science knows nothing. Science knows enough for us to be watched by a few million people now on television, for these lights to be working, for quite extraordinary miracles to have taken place in terms of the harnessing of the physical world and our dim approaches towards understanding it.", "Stephen Fry"],
  ["Science and art belong to the whole world, and before them vanish the barriers of nationality.", "Johann Wolfgang von Goethe"],
  ["Science embraces facts and debates opinion; religion embraces opinion and debates the facts.", "Tom Heehler"],
  ["Modern civilization depends on science … James Smithson was well aware that knowledge should not be viewed as existing in isolated parts, but as a whole, each portion of which throws light on all the other, and that the tendency of all is to improve the human mind, and give it new sources of power and enjoyment … narrow minds think nothing of importance but their own favorite pursuit, but liberal views exclude no branch of science or literature, for they all contribute to sweeten, to adorn, and to embellish life … science is the pursuit above all which impresses us with the capacity of man for intellectual and moral progress and awakens the human intellect to aspiration for a higher condition of humanity.", "Joseph Henry"],
  ["Take from the air every aëroplane; from the roads every automobile; from the country every train; from the cities every electric light; from ships even wireless apparatus; from oceans all cables; from the land all wires; from shops all motors; from office buildings every elevator, telephone, and typewriter; let epidemics spread at will; let major surgery be impossible—all this and vastly more, the bondage of ignorance, where knowledge now makes us free, would be the terrible catastrophe if the tide of time should but ebb to the childhood days of men still living! ...Therefore, whoever desires progress and prosperity, whoever would advance humanity to a higher plane of civilization, must further the work of the scientist in every way he possibly can.", "William J. Humphreys"],
  ["Some people think that science is just all this technology around, but NO it's something much deeper than that. Science, scientific thinking, scientific method is for me the only philosophical construct that the human race has developed to determine what is reliably true.", "Sir Harry Kroto"],
  ["With respect to science, the assumption behind consensus is that science is a source of authority and that authority increases with the number of scientists. Of course, science is not primarily a source of authority. Rather, it is a particularly effective approach to inquiry and analysis. Skepticism is essential to science; consensus is foreign.", "Richard S. Lindzen"],
  ["We'll try to imitate how Galileo and Newton learned so much by studying the simplest kinds of pendulums and weights, mirrors and prisms. ...It is the same reason why so many biologists today devote more attention to tiny germs and viruses than to magnificent lions and tigers. ...In science, one can learn the most by studying what seems the least.", "Marvin Minsky"],
  ["It is not in the nature of things for any one man to make a sudden violent discovery; science goes step by step, and every man depends on the work of his predecessors. When you hear of a sudden unexpected discovery—a bolt from the blue, as it were—you can always be sure that it has grown up by the influence of one man on another, and it is this mutual influence which makes the enormous possibility of scientific advance. Scientists are not dependent on the ideas of a single man, but on the combined wisdom of thousands of men, all thinking of the same problem, and each doing his little bit to add to the great structure of knowledge which is gradually being erected.", "Ernest Rutherford"],
  ["Science is much more than a body of knowledge. It is a way of thinking. This is central to its success. Science invites us to let the facts in, even when they don’t conform to our preconceptions. It counsels us to carry alternative hypotheses in our heads and see which ones best match the facts. It urges on us a fine balance between no-holds-barred openness to new ideas, however heretical, and the most rigorous skeptical scrutiny of everything — new ideas and established wisdom. We need wide appreciation of this kind of thinking. It works. It’s an essential tool for a democracy in an age of change. Our task is not just to train more scientists but also to deepen public understanding of science.", "Carl Sagan"],
  ["A central lesson of science is that to understand complex issues (or even simple ones), we must try to free our minds of dogma and to guarantee the freedom to publish, to contradict, and to experiment. Arguments from authority are unacceptable.", "Carl Sagan"],
  ["Scientific skepticism is considered good. […] Under this principle, one must question, doubt, or suspend judgment until sufficient information is available. Skeptics demand that evidence and proof be offered before conclusions can be drawn. […] One must thoughtfully gather evidence and be persuaded by the evidence rather than by prejudice, bias, or uncritical thinking.", "Sue Stanley"],
  ["All the great revolutions in science start with an unexpected discrepancy that wouldn’t go away.", "Matthew Strassler"],
  ["I often say that when you can measure what you are speaking about, and express it in numbers, you know something about it; but when you cannot measure it, when you cannot express it in numbers, your knowledge is of a meagre and unsatisfactory kind; it may be the beginning of knowledge, but you have scarcely, in your thoughts, advanced to the stage of science, whatever the matter may be.", "William Thomson (Lord Kelvin)"],
  ["There is a noticeable general difference between the sciences and mathematics on the one hand, and the humanities and social sciences on the other. It's a first approximation, but one that is real. In the former, the factors of integrity tend to dominate more over the factors of ideology. It's not that scientists are more honest people. It's just that nature is a harsh taskmaster. You can lie or distort the story of the French Revolution as long as you like, and nothing will happen. Propose a false theory in chemistry, and it'll be refuted tomorrow.", "Noam Chomsky"],
  ["What is a scientist after all? It is a curious person looking through a keyhole, the keyhole of nature, trying to know what's going on.", "Jacques-Yves Cousteau"],
  ["Scientists are just as vulnerable to wishful thinking, just as likely to be tempted by base motives, just as venal and gullible and forgetful as the rest of humankind. Scientists don't consider themselves to be saints; they don't even pretend to be priests (who according to tradition are supposed to do a better job than the rest of us at fighting off human temptation and frailty). Scientists take themselves to be just as weak and fallible as anybody else, but recognizing those very sources of error in themselves and in the groups to which they belong, they have devised elaborate systems to tie their own hands, forcibly preventing their frailties and prejudices from infecting their results.", "Daniel Dennett"],
  ["The scientist is possessed by the sense of universal causation. The future, to him, is every whit as necessary and determined as the past. There is nothing divine about morality, it is a purely human affair...", "Albert Einstein"],
  ["The genuine scientist is not moved by praise or blame, nor does he preach. He unveils the universe and people come eagerly, without being pushed, to behold a new revelation: the order, the harmony, the magnificence of creation! And as man becomes conscious of the stupendous laws that govern the universe in perfect harmony, he begins to realize how small he is. He sees the pettiness of human existence, with its ambitions and intrigues, its 'I am better than thou' creed. This is the beginning of cosmic religion within him; fellowship and human service become his moral code. And without such moral foundations, we are hopelessly doomed.", "Albert Einstein"],
  ["My profession often gets bad press for a variety of sins, both actual and imagined: arrogance, venality, insensitivity to moral issues about the use of knowledge, pandering to sources of funding with insufficient worry about attendant degradation of values. As an advocate for science, I plead “mildly guilty now and then” to all these charges. Scientists are human beings subject to all the foibles and temptations of ordinary life. Some of us are moral rocks; others are reeds. I like to think (though I have no proof) that we are better, on average, than members of many other callings on a variety of issues central to the practice of good science: willingness to alter received opinion in the face of uncomfortable data, dedication to discovering and publicizing our best and most honest account of nature's factuality, judgment of colleagues on the might of their ideas rather than the power of their positions.", "Stephen Jay Gould"],
  ["There must be no barriers for freedom of inquiry. There is no place for dogma in science. The scientist is free, and must be free to ask any question, to doubt any assertion, to seek for any evidence, to correct any errors.", "Robert Oppenheimer"],
  ["A scientist is happy, not in resting on his attainments but in the steady acquisition of fresh knowledge.", "Max Planck"],
  ["In science it often happens that scientists say, \"You know that's a really good argument; my position is mistaken,\" and then they would actually change their minds and you never hear that old view from them again. They really do it. It doesn't happen as often as it should, because scientists are human and change is sometimes painful. But it happens every day. I cannot recall the last time something like that happened in politics or religion.", "Carl Sagan"],
   ["It is sometimes said that scientists are unromantic, that their passion to figure out robs the world of beauty and mystery. But is it not stirring to understand how the world actually works — that white light is made of colors, that color is the way we perceive the wavelengths of light, that transparent air reflects light, that in so doing it discriminates among the waves, and that the sky is blue for the same reason that the sunset is red? It does no harm to the romance of the sunset to know a little bit about it.", "Carl Sagan"]
]

//https://en.wikiquote.org/wiki/Scientists

getQuote = function() {
  var q = Math.floor(Math.random() * quotes.length);
  return "<p>" + quotes[q][0] + "</p><p>-" + quotes[q][1];
}

$(document).ready(function() {
  $("#quote").append(getQuote());
  $("#gen").click(function() {
    $('#quote').empty();
    $("#quote").append(getQuote());
  });
});